# Generated by Django 4.2.4 on 2023-08-16 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_genre_description_alter_game_developer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id'], 'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
