# Generated by Django 4.2.4 on 2023-08-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='developer',
            new_name='studio',
        ),
    ]
